
export const SECRET_SALT = "DUSARYA_APP_CHA_SALT_2025"; 
export const MASTER_ADMIN_PIN = "FICUSAI1111";
export const APP_VERSION = "2.5.1-PSYCH-FICUS";
export const SUPPORT_WHATSAPP = "919987961609";

export const TRANSLATIONS = {
  mr: {
    appTitle: "Trade Psychology",
    subtitle: "Discipline Master System",
    idPlaceholder: "उदा: AMIT-TRADER",
    idLabel: "१. तुमचा आयडी टाका (उदा: तुमचे नाव)",
    keyLabel: "२. लायसन्स की टाका",
    unlockBtn: "अ‍ॅप अनलॉक करा",
    requestBtn: "लायसन्स की हवी आहे?",
    adminRequest: "अ‍ॅडमिनला विनंती करा",
    helpCenter: "मदत केंद्र",
    disciplineHub: "शिस्त केंद्र",
    performanceLog: "ट्रेड जर्नल",
    personalDiary: "वैयक्तिक डायरी",
    ficusCoach: "Ficus AI कोच",
    universalLaws: "नियम व विचारधारा",
    settings: "सेटिंग्ज",
    disciplineStreak: "शिस्त स्ट्रीक",
    ultimateGoal: "परम लक्ष्य: ११११ दिवस",
    successPhilosophy: "जर तुम्ही ११११ दिवस शिस्तबद्ध पद्धतीने ट्रेड केला, तर तुम्हाला यशस्वी होण्यापासून कोणीच थांबवू शकत नाही.",
    days: "दिवस",
    divineDiscipline: "दिव्य शिस्त",
    alignment: "बाजारपूर्व तयारी",
    harmony: "शांतता",
    protocolActive: "प्रोटोकॉल सक्रिय",
    focusCalibration: "बलून फोकस टेस्ट",
    focusDesc: "फुगे फोडून तुमची एकाग्रता तपासा.",
    startCalibration: "चाचणी सुरू करा",
    hits: "फोडल",
    mindAligned: "मन स्थिर झाले आहे",
    auraCleared: "मन शांत: तुम्ही तयार आहात",
    integrityScore: "शिस्त गुण",
    rulesAdherence: "नियम पालन",
    enlightenedJournal: "दिव्य जर्नल",
    newEntry: "नवीन ट्रेड नोंद",
    journalLocked: "जर्नल लॉक आहे",
    journalLockDesc: "जर्नलमध्ये प्रवेश करण्यासाठी प्रथम 'बाजारपूर्व तयारी' आणि 'एकाग्रता चाचणी' पूर्ण करा.",
    beginRoutine: "तयारी सुरू करा",
    zenIntro: "स्वागत आहे! मी 'Ficus AI' आहे. तुमच्या ट्रेडिंग प्रवासातील मानसिक शांततेसाठी मी येथे आहे. आज काय चर्चा करायची?",
    placeholderCoach: "तुमची मानसिक स्थिती सांगा...",
    language: "भाषा निवडा",
    logout: "लॉगआउट",
    gameNextPrompt: "पुन्हा एकाग्रता वाढवायची आहे का?",
    gameYes: "हो, अजून शांत व्हायचे आहे",
    gameNo: "नाही, आता मी तयार आहे",
    gameCalm: "तुमचा मेंदू आता अधिक शांत आणि हुशार होत आहे.",
    level: "पातळी",
    preTrade: "प्री-ट्रेड (सक्रिय)",
    postTrade: "पोस्ट-ट्रेड (इतिहास)",
    segment: "सेगमेंट",
    symbol: "सिम्बॉल",
    qty: "क्वांटिटी",
    entryPrice: "एंट्री प्राईस",
    slPrice: "SL प्राईस",
    targetPrice: "टार्गेट प्राईस",
    exitPrice: "एक्झिट प्राईस",
    emotion: "भावना/स्थिती",
    uploadImage: "फोटो अपलोड करा",
    saveTrade: "ट्रेड सेव्ह करा",
    closeTrade: "ट्रेड क्लोज करा",
    profit: "नफा",
    loss: "तोटा",
    pnlLabel: "एकूण नफा/तोटा",
    riskAmount: "जोखीम",
    rewardAmount: "अपेक्षित नफा",
    points: "पॉइंट्स",
    successRate: "यशस्वी दर",
    dayReturn: "आजचा परतावा",
    weekReturn: "आठवड्याचा परतावा",
    monthReturn: "महिन्याचा परतावा",
    yearReturn: "वर्षाचा परतावा",
    status: "स्थिती",
    entered: "तारीख",
    returnPct: "परतावा %",
    tradingExpectancy: "ट्रेडिंग अपेक्षीत नफा (Avg)",
    weeklyPerformance: "साप्ताहिक कामगिरी",
    mon: "सोम", tue: "मंगळ", wed: "बुध", thu: "गुरू", fri: "शुक्र",
    diaryPlaceholder: "आज तुमचे मन काय म्हणते आहे? तुमचे विचार लिहा...",
    saveDiary: "डायरी नोंदवा",
    personalMentors: "माझे आदर्श ट्रेडर आणि विचारधारा",
    addMentor: "नवीन आदर्श जोडा",
    mentorName: "ट्रेडरचे नाव",
    mentorLesson: "त्यांच्याकडून काय शिकलात?",
    saveMentor: "जोडा",
    waTemplate: (id: string, token: string) => `*TRADE PSYCHOLOGY ACTIVATION*\n--------------------------\nनमस्ते अ‍ॅडमिन,\nमला अ‍ॅप सुरू करण्यासाठी लायसन्स की हवी आहे.\n\n*माझा तपशील:*\n🆔 ID: ${id}\n🔑 Token: ${token}\n--------------------------\nकृपया ही की जनरेटरमध्ये पेस्ट करून मला लायसन्स की पाठवा.`,
    routineItems: [
      "मी आजचा ट्रेडिंग प्लॅन नीट वाचला आहे.",
      "मी माझी रिस्क (Stop Loss) ठरवली आहे.",
      "मी आज बदल्याच्या भावनेत ट्रेड करणार नाही.",
      "मी फक्त माझ्या सेटअपवरच ट्रेड घेईन.",
      "मी मार्केटमधील नफ्यापेक्षा माझ्या शिस्तीला महत्त्व देईन."
    ],
    goldenRules: [
      { title: "Risk Management", text: "प्रत्येक ट्रेडमध्ये कॅपिटलच्या १% पेक्षा जास्त रिस्क घेऊ नका." },
      { title: "Patience", text: "सेटअप बनल्याशिवाय मार्केटमध्ये उडी मारू नका." },
      { title: "Execution", text: "तुमच्या प्लॅनला चिकटून राहा, इमोशन्सला नाही." },
      { title: "Review", text: "दिवसाच्या शेवटी लॉस झाला तरी तो शांतपणे एक्सेप्ट करा." }
    ],
    biases: [
      "Loss Aversion (नुकसानीची भीती)",
      "FOMO (संधी हुकण्याची भीती)",
      "Confirmation Bias (केवळ स्वतःला हवे तेच बघणे)",
      "Recency Bias (ताज्या नफ्या-तोट्याचा प्रभाव)"
    ],
    affirmations: [
      "मी एक शिस्तबद्ध ट्रेडर आहे.",
      "माझा नफा माझ्या संयमावर अवलंबून आहे.",
      "मी मार्केटला कंट्रोल करू शकत नाही, पण मी माझ्या भावनांना कंट्रोल करू शकतो.",
      "नियम पाळणे हे नफा मिळवण्यापेक्षा जास्त महत्त्वाचे आहे."
    ]
  },
  hi: {
    appTitle: "Trade Psychology",
    subtitle: "Discipline Master System",
    idPlaceholder: "उदा: AMIT-TRADER",
    idLabel: "१. अपनी आईडी डालें (उदा: आपका नाम)",
    keyLabel: "२. लाइसेंस की डालें",
    unlockBtn: "ऐप अनलॉक करें",
    requestBtn: "लाइसेंस की चाहिए?",
    adminRequest: "अ‍ॅडमिन से अनुरोध करें",
    helpCenter: "सहायता केंद्र",
    disciplineHub: "अनुशासन केंद्र",
    performanceLog: "ट्रेड जर्नल",
    personalDiary: "व्यक्तिगत डायरी",
    ficusCoach: "Ficus AI कोच",
    universalLaws: "नियम और विचारधारा",
    settings: "सेटिंग्स",
    disciplineStreak: "अनुशासन स्ट्रीक",
    ultimateGoal: "परम लक्ष्य: 1111 दिन",
    successPhilosophy: "यदि आप 1111 दिनों तक अनुशासन के साथ ट्रेड करते हैं, तो आपको सफल होने से कोई नहीं रोक सकता।",
    days: "दिन",
    divineDiscipline: "दिव्य अनुशासन",
    alignment: "बाजार पूर्व तैयारी",
    harmony: "सामंजस्य",
    protocolActive: "प्रोटोकॉल सक्रिय",
    focusCalibration: "बलून फोकस टेस्ट",
    focusDesc: "गुब्बारे फोड़कर अपनी एकाग्रता की जांच करें।",
    startCalibration: "परीक्षण शुरू करें",
    hits: "फोड़ा",
    mindAligned: "मन संरेखित है",
    auraCleared: "मन शांत: आप तैयार हैं",
    integrityScore: "अखंडता स्कोर",
    rulesAdherence: "नियम पालन",
    enlightenedJournal: "प्रबुद्ध जर्नल",
    newEntry: "नई ट्रेड एंट्री",
    journalLocked: "इनर सर्कल लॉक",
    journalLockDesc: "जर्नल तक पहुंचने के लिए पहले 'बाजार पूर्व तैयारी' और 'एकाग्रता परीक्षण' पूरा करें।",
    beginRoutine: "तयारी शुरू करें",
    zenIntro: "स्वागत है! मैं 'Ficus AI' हूँ। मैं आपकी ट्रेडिंग यात्रा में मानसिक शांति के लिए यहाँ हूँ। आज क्या चर्चा करें?",
    placeholderCoach: "अपनी मानसिक स्थिति बताएं...",
    language: "भाषा चुनें",
    logout: "लॉगआउट",
    gameNextPrompt: "क्या आप फिर से एकाग्रता बढ़ाना चाहते हैं?",
    gameYes: "हाँ, और शांत होना है",
    gameNo: "नहीं, अब मैं तैयार हूँ",
    gameCalm: "आपका मस्तिष्क अब अधिक शांत और बुद्धिमान हो रहा है।",
    level: "स्तर",
    preTrade: "प्री-ट्रेड (सक्रिय)",
    postTrade: "पोस्ट-ट्रेड (इतिहास)",
    segment: "सेगमेंट",
    symbol: "सिंबल",
    qty: "मात्रा",
    entryPrice: "एंट्री प्राइस",
    slPrice: "SL प्राइस",
    targetPrice: "टार्गेट प्राइस",
    exitPrice: "एग्जिट प्राइस",
    emotion: "भावना/स्थिति",
    uploadImage: "छवि अपलोड करें",
    saveTrade: "ट्रेड सुरक्षित करें",
    closeTrade: "ट्रेड बंद करें",
    profit: "लाभ",
    loss: "हानि",
    pnlLabel: "कुल लाभ/हानि",
    riskAmount: "जोखिम राशि",
    rewardAmount: "अपेक्षित लाभ",
    points: "अंक",
    successRate: "सफलता दर",
    dayReturn: "आज का लाभ",
    weekReturn: "साप्ताहिक लाभ",
    monthReturn: "मासिक लाभ",
    yearReturn: "वार्षिक लाभ",
    status: "स्थिति",
    entered: "तिथि",
    returnPct: "रिटर्न %",
    tradingExpectancy: "ट्रेडिंग एक्सपेक्टेंसी (Avg)",
    weeklyPerformance: "साप्ताहिक प्रदर्शन",
    mon: "सोम", tue: "मंगल", wed: "बुध", thu: "गुरु", fri: "शुक्र",
    diaryPlaceholder: "आज आपके मन में क्या चल रहा है? अपने विचार लिखें...",
    personalMentors: "मेरे आदर्श ट्रेडर और विचारधारा",
    addMentor: "नया आदर्श जोड़ें",
    mentorName: "ट्रेडर का नाम",
    mentorLesson: "उनसे क्या सीखा?",
    saveMentor: "सहेजें",
    waTemplate: (id: string, token: string) => `*TRADE PSYCHOLOGY ACTIVATION*\n--------------------------\nनमस्ते एडमिन,\nमुझे ऐप शुरू करने के लिए लाइसेंस की चाहिए।\n\n*मेरा विवरण:*\n🆔 ID: ${id}\n🔑 Token: ${token}\n--------------------------\nकृपया इस की को जनरेटर में पेस्ट करके मुझे लाइसेंस की भेजें। धन्यवाद।`,
    routineItems: [
      "मैंने आज का ट्रेडिंग प्लान पढ़ लिया है।",
      "मैंने अपना जोखिम (Stop Loss) निर्धारित कर लिया है।",
      "मैं आज बदले की भावना से ट्रेड नहीं करूँगा।",
      "मैं केवल अपने सेटअप पर ही ट्रेड करूँगा।",
      "मैं लाभ से अधिक अपने अनुशासन को महत्व दूँगा।"
    ],
    goldenRules: [
      { title: "Risk Management", text: "प्रत्येक ट्रेड में अपनी पूंजी के १% से अधिक जोखिम न लें।" },
      { title: "Patience", text: "जब तक सेटअप न बने, बाजार में प्रवेश न करें।" },
      { title: "Execution", text: "अपनी योजना पर टिके रहें, भावनाओं पर नहीं।" },
      { title: "Review", text: "दिन के अंत में नुकसान होने पर भी उसे शांति से स्वीकार करें।" }
    ],
    biases: [
      "Loss Aversion (नुकसान का डर)",
      "FOMO (छूटने का डर)",
      "Confirmation Bias (सिर्फ वही देखना जो आप चाहते हैं)",
      "Recency Bias (हालिया लाभ/हानि का प्रभाव)"
    ],
    affirmations: [
      "मैं एक अनुशासित ट्रेडर हूँ।",
      "मेरा लाभ मेरे धैर्य पर निर्भर करता है।",
      "मैं बाजार को नियंत्रित नहीं कर सकता, लेकिन अपनी भावनाओं को कर सकता हूँ।",
      "नियमों का पालन करना लाभ कमाने से अधिक महत्वपूर्ण है।"
    ]
  },
  en: {
    appTitle: "Trade Psychology",
    subtitle: "Discipline Master System",
    idPlaceholder: "e.g. AMIT-TRADER",
    idLabel: "1. Enter your System ID (Your Name)",
    keyLabel: "2. Enter License Key",
    unlockBtn: "Unlock Application",
    requestBtn: "Need a License Key?",
    adminRequest: "Request from Admin",
    helpCenter: "Help Center",
    disciplineHub: "Discipline Hub",
    performanceLog: "Performance Log",
    personalDiary: "Personal Diary",
    ficusCoach: "Ficus AI Coach",
    universalLaws: "Laws & Ideology",
    settings: "Settings",
    disciplineStreak: "Discipline Streak",
    ultimateGoal: "Ultimate Goal: 1111 Days",
    successPhilosophy: "If you trade with discipline for 1111 days, no one can stop you from being a successful trader.",
    days: "Days",
    divineDiscipline: "Divine Discipline",
    alignment: "Pre-Market Alignment",
    harmony: "Harmony",
    protocolActive: "Protocol Active",
    focusCalibration: "Balloon Focus Test",
    focusDesc: "Pop balloons to test your focus.",
    startCalibration: "Start Calibration",
    hits: "Popped",
    mindAligned: "Mind Aligned",
    auraCleared: "Aura Cleared: Ready",
    integrityScore: "Integrity Score",
    rulesAdherence: "Rules Adherence",
    enlightenedJournal: "Enlightened Journal",
    newEntry: "New Trade Entry",
    journalLocked: "Journal Locked",
    journalLockDesc: "To access the journal, complete Alignment and Focus Calibration first.",
    beginRoutine: "Begin Preparation",
    zenIntro: "Welcome! I am 'Ficus AI'. I am here for your mental peace during your trading journey. What shall we discuss today?",
    placeholderCoach: "Describe your mental state...",
    language: "Select Language",
    logout: "Logout",
    gameNextPrompt: "Increase focus again?",
    gameYes: "Yes, I want more peace",
    gameNo: "No, I am ready now",
    gameCalm: "Your mind is becoming calmer, sharper, and smarter.",
    level: "Level",
    preTrade: "Pre-Trade (Active)",
    postTrade: "Post-Trade (History)",
    segment: "Segment",
    symbol: "Symbol",
    qty: "Qty",
    entryPrice: "Entry Price",
    slPrice: "SL Price",
    targetPrice: "Target Price",
    exitPrice: "Exit Price",
    emotion: "Emotion/State",
    uploadImage: "Upload Image",
    saveTrade: "Save Trade",
    closeTrade: "Close Trade",
    profit: "Profit",
    loss: "Loss",
    pnlLabel: "Total P&L",
    riskAmount: "Risk Amt",
    rewardAmount: "Reward Amt",
    points: "Pts",
    successRate: "Success Rate",
    dayReturn: "Day Return",
    weekReturn: "Week Return",
    monthReturn: "Month Return",
    yearReturn: "Year Return",
    status: "Status",
    entered: "Date",
    returnPct: "Return %",
    tradingExpectancy: "Trading Expectancy (Avg)",
    weeklyPerformance: "Weekly Performance",
    mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri",
    diaryPlaceholder: "What's on your mind today? Write your thoughts...",
    personalMentors: "My Mentors & Ideologies",
    addMentor: "Add Personal Ideology",
    mentorName: "Trader/Personality Name",
    mentorLesson: "Core Lesson Learned",
    saveMentor: "Save",
    waTemplate: (id: string, token: string) => `*TRADE PSYCHOLOGY ACTIVATION*\n--------------------------\nHello Admin,\nI need a license key to start the app.\n\n*My Details:*\n🆔 ID: ${id}\n🔑 Token: ${token}\n--------------------------\nPlease paste this token in the generator and send me the key. Thanks!`,
    routineItems: [
      "I have read my trading plan thoroughly.",
      "I have defined my risk per trade.",
      "I will not engage in revenge trading today.",
      "I will only trade my specific setups.",
      "I value my discipline over market profits."
    ],
    goldenRules: [
      { title: "Risk Management", text: "Never risk more than 1% of your total capital on a single trade." },
      { title: "Patience", text: "Do not jump into the market unless your setup is fully formed." },
      { title: "Execution", text: "Stick to your plan, not to your emotions." },
      { title: "Review", text: "Accept your losses gracefully at the end of the day." }
    ],
    biases: [
      "Loss Aversion (Fear of loss)",
      "FOMO (Fear of missing out)",
      "Confirmation Bias (Only seeing what suits you)",
      "Recency Bias (Impact of recent win/loss)"
    ],
    affirmations: [
      "I am a disciplined trader.",
      "My profits depend on my patience.",
      "I cannot control the market, but I can control my emotions.",
      "Following rules is more important than catching the move."
    ]
  }
};
